version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=ZORO
      - POSTGRES_PASSWORD=secretfornow
      - POSTGRES_DB=shortener
    ports:
      - "5432:5432"
    volumes:
      -db-data: /var/lib/postgresql/data

volumes:
  db-data: 
